apiVersion: v1 
kind: Service 
metadata:
  name: spring-argo
  namespace: default 
spec:
  selector:
    app: spring-argo  
  type: NodePort
  ports: 
    - port: 8080
      targetPort: 8080   
      nodePort: 30090 
